<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>

		<PackageId>ApacheZooKeeper.Recipes</PackageId>
		<PackageDescription>ZooKeeper Recipes</PackageDescription>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Authors>hippasus</Authors>
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ApacheZooKeeper\ApacheZooKeeper.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>
