namespace ApacheZooKeeper;

public abstract class Watcher
{
    public abstract void process(WatchedEvent @event);

    public static class Event
    {
        public enum KeeperState
        {
            /// <summary>
            /// Unused, this state is never generated by the server.
            /// </summary>
            [Obsolete]
            Unknown = -1,

            /// <summary>
            /// The client is in the disconnected state - it is not connected to any server in the ensemble.
            /// </summary>
            Disconnected = 0,

            /// <summary>
            /// Unused, this state is never generated by the server.
            /// </summary>
            [Obsolete]
            NoSyncConnected = 1,

            /// <summary>
            /// The client is in the connected state - it is connected to a server in the ensemble.
            /// </summary>
            SyncConnected = 3,

            /// <summary>
            /// Auth failed state.
            /// </summary>
            AuthFailed = 4,

            /// <summary>
            /// The client is connected to a read-only server.
            /// </summary>
            ConnectedReadOnly = 5,

            /// <summary>
            /// SaslAuthenticated: used to notify clients that they are SASL-authenticated.
            /// </summary>
            SaslAuthenticated = 6,

            /// <summary>
            /// The serving cluster has expired this session.
            /// </summary>
            Expired = -112,

            /// <summary>
            /// The client has been closed. This state is never generated by the server.
            /// </summary>
            Closed = 7
        }

        public enum EventType
        {
            None = -1,
            NodeCreated = 1,
            NodeDeleted = 2,
            NodeDataChanged = 3,
            NodeChildrenChanged = 4,
            DataWatchRemoved = 5,
            ChildWatchRemoved = 6,
            PersistentWatchRemoved = 7
        }
    }

    public enum WatcherType
    {
        Children = 1,
        Data = 2,
        Any = 3,
        Persistent = 4,
        PersistentRecursive = 5
    }
}

public static class KeeperStateExtensions
{
    public static int getIntValue(this Watcher.Event.KeeperState keeperState)
    {
        return (int)keeperState;
    }

    public static Watcher.Event.KeeperState fromInt(int intValue)
    {
        return intValue switch
        {
            -1 => Watcher.Event.KeeperState.Unknown,
            0 => Watcher.Event.KeeperState.Disconnected,
            1 => Watcher.Event.KeeperState.NoSyncConnected,
            3 => Watcher.Event.KeeperState.SyncConnected,
            4 => Watcher.Event.KeeperState.AuthFailed,
            5 => Watcher.Event.KeeperState.ConnectedReadOnly,
            6 => Watcher.Event.KeeperState.SaslAuthenticated,
            -112 => Watcher.Event.KeeperState.Expired,
            7 => Watcher.Event.KeeperState.Closed,
            _ => throw new ArgumentException("Invalid integer value for conversion to KeeperState")
        };
    }
}

public static class EventTypeExtensions
{
    public static int getIntValue(this Watcher.Event.EventType eventType)
    {
        return (int)eventType;
    }

    public static Watcher.Event.EventType fromInt(int intValue)
    {
        return intValue switch
        {
            -1 => Watcher.Event.EventType.None,
            1 => Watcher.Event.EventType.NodeCreated,
            2 => Watcher.Event.EventType.NodeDeleted,
            3 => Watcher.Event.EventType.NodeDataChanged,
            4 => Watcher.Event.EventType.NodeChildrenChanged,
            5 => Watcher.Event.EventType.DataWatchRemoved,
            6 => Watcher.Event.EventType.ChildWatchRemoved,
            7 => Watcher.Event.EventType.PersistentWatchRemoved,
            _ => throw new ArgumentException("Invalid integer value for conversion to EventType")
        };
    }
}

public static class WatcherTypeExtensions
{
    public static int getIntValue(this Watcher.WatcherType watcherType)
    {
        return (int)watcherType;
    }

    public static Watcher.WatcherType fromInt(int intValue)
    {
        return intValue switch
        {
            1 => Watcher.WatcherType.Children,
            2 => Watcher.WatcherType.Data,
            3 => Watcher.WatcherType.Any,
            4 => Watcher.WatcherType.Persistent,
            5 => Watcher.WatcherType.PersistentRecursive,
            _ => throw new ArgumentException("Invalid integer value for conversion to WatcherType")
        };
    }
}
